version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD : "yes"
      MARIADB_USER: 'symfony'
      MARIADB_PASSWORD: '123456789'
      MARIADB_DATABASE: "db_group3"

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
